AA_tbl <- data.table::setnames(data.table::rbindlist(list(c(list("I"), list(6, 13, 1, 2, 0)),
                                  c(list("L"), list(6, 13, 1, 2, 0)),
                                  c(list("K"), list(6, 14, 2, 2, 0)),
                                  c(list("M"), list(5, 11, 1, 2, 1)),
                                  c(list("F"), list(9, 11, 1, 2, 0)),
                                  c(list("T"), list(4, 9, 1, 3, 0)),
                                  c(list("W"), list(11, 12, 2, 2, 0)),
                                  c(list("V"), list(5, 11, 1, 2, 0)),
                                  c(list("R"), list(6, 14, 4, 2, 0)),
                                  c(list("H"), list(6, 9, 3, 2, 0)),
                                  c(list("A"), list(3, 7, 1, 2, 0)),
                                  c(list("N"), list(4, 8, 2, 3, 0)),
                                  c(list("D"), list(4, 7, 1, 4, 0)),
                                  c(list("C"), list(3, 7, 1, 2, 1)),
                                  c(list("E"), list(5, 9, 1, 4, 0)),
                                  c(list("Q"), list(5, 10, 2, 3, 0)),
                                  c(list("G"), list(2, 5, 1, 2, 0)),
                                  c(list("P"), list(5, 9, 1, 2, 0)),
                                  c(list("S"), list(3, 7, 1, 3, 0)),
                                  c(list("Y"), list(9, 11, 1, 3, 0)))),
                   c("AA", "C", "H", "N", "O", "S"))

